- name: Run Datapatch
  shell: |
       export ORACLE_HOME ORACLE_SID
       ./datapatch -verbose >> /tmp/datapatch.{{ file_suffix }}_{{ datapatch_try }}.log 2>&1
  environment:
    ORACLE_HOME: "{{ dbhome_locl }}"
    ORACLE_SID: "{{ mysid }}"
  args:
    chdir: "{{ dbhome_locl }}/OPatch"
  register: datapatch_exec
  become: true
  become_user: oracle
  delegate_to: "{{ vm_ip_address }}"
  ignore_errors: yes
  # Variable export and chdir introduced to solve an issue in 12.1.0.1 PSU 7 - Patch 20299016
  
- name: Datapatch output
  debug: msg="{{ datapatch_exec.stdout_lines }}"
  when: datapatch_exec.stdout_lines is defined

##### If datapatch is OK !
- block:

  - name: "Check if datapatch has extra patches to apply"
    shell: |
         set -eo pipefail
         export ORACLE_HOME ORACLE_SID
         # Try twice as it can fail with: Queryable inventory could not determine the current opatch status.
         v_out=$(./datapatch -prereq) || v_out=$(./datapatch -prereq)
         echo "${v_out}" | grep -q 'The following patches will be applied' && echo has_more_patch || echo no_more_patch
    environment:
      ORACLE_HOME: "{{ dbhome_locl }}"
      ORACLE_SID: "{{ mysid }}"
    args:
      chdir: "{{ dbhome_locl }}/OPatch"
    register: datapatch_check
    become: true
    become_user: oracle
    delegate_to: "{{ vm_ip_address }}"

  - name: Check Result
    debug: msg="{{ datapatch_check.stdout }}"

  - name: Increment variable
    set_fact: datapatch_try={{ datapatch_try | int + 1 }}
    when: datapatch_check.stdout == "has_more_patch"

  - name: Datapatch Error
    fail:
      msg: "Datapatch still has things to apply."
    when:
      - datapatch_check.stdout == "has_more_patch"
      - (datapatch_try | int) > (fix_datapatch_retries | int)

  - name: Re-exec datapatch
    include: datapatch.yml
    when:
      - datapatch_check.stdout == "has_more_patch"
      - (datapatch_try | int) <= (fix_datapatch_retries | int)

  when: datapatch_exec.rc == 0

##### If datapatch is not OK !
- block:

  - name: Increment variable
    set_fact: datapatch_try={{ datapatch_try | int + 1 }}

  - name: Datapatch Error
    fail:
      msg: "Datapatch execution failed."
    when: (datapatch_try | int) > (fix_datapatch_retries | int)

  - name: Re-exec datapatch
    include: datapatch.yml
    when:
      - (datapatch_try | int) <= (fix_datapatch_retries | int)

  when: datapatch_exec.rc != 0

##########################################################